insightsengineering/teal.modules.general

- DESCRIPTION
- R/tm_a_pca.R
Part of insightsengineering/teal.slice#33 
See more here: https://github.com/insightsengineering/teal.slice/pull/49
> remove datasets$get_data_attr call

- R/tm_a_regression.R
- R/tm_g_distribution.R
- R/tm_missing_data.R
- R/tm_variable_browser.R
- R/utils.R
Update font awesome icon labels for FA 6, to avoid warnings like:
```
This Font Awesome icon ('some icon') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
be deactivated with `verify_fa = FALSE`
```
> Update font awesome icon labels for FA 6

- R/tm_missing_data.R
- R/tm_outliers.R
Part of https://github.com/insightsengineering/teal.slice/issues/76
> remove filtered

- NEWS.md
- R/tm_data_table.R
- man/tm_data_table.Rd
Closes #442 fyi @npaszty 
Test with e.g.
```
library(teal.modules.general)
library(scda)
server_rendering <- TRUE # or set to FALSE
ADSL <- synthetic_cdisc_data("latest")$adsl
ADTTE <- synthetic_cdisc_data("latest")$adtte
app <- init(
data = cdisc_data(
cdisc_dataset("ADSL", ADSL, code = "ADSL <- synthetic_cdisc_data(\"latest\")$adsl"),
cdisc_dataset("ADTTE", ADTTE, code = "ADTTE <- synthetic_cdisc_data(\"latest\")$adtte"),
check = TRUE
),
tm_data_table(
dt_args = list(extensions = c("Buttons", "ColReorder", "FixedHeader")),
dt_options = list(
searching = FALSE,
pageLength = 30,
lengthMenu = c(5, 15, 25, 50, 100),
scrollX = FALSE,
dom = "lBrtip",
buttons = c("copy", "csv", "excel", "pdf", "print"),
colReorder = TRUE,
fixedHeader = TRUE
),
server_rendering = …
```
> server_rendering argument to `tm_data_table`

- NEWS.md
- R/tm_t_crosstable.R
closes #451 
Fixed the join type functionality in the `tm_t_crosstable`.
> fix join_fun crosstable

- R/tm_missing_data.R
addresses the first part of https://github.com/insightsengineering/teal.modules.general/issues/471
Dataset name added to card title and to the plot title.
Please test with example app.
> tm_missing_data: add dataname to report

- R/tm_front_page.R
Closes https://github.com/insightsengineering/coredev-tasks/issues/376
Test with 
```
library(scda)
library(teal.modules.general)
table_1 <- data.frame(Info = c("A", "B"), Text = c("A", "B"))
table_2 <- data.frame(`Column 1` = c("C", "D"), `Column 2` = c(5.5, 6.6), `Column 3` = c("A", "B"))
table_3 <- data.frame(Info = c("E", "F"), Text = c("G", "H"))
table_input <- list(
"Table 1" = table_1,
"Table 2" = table_2,
"Table 3" = table_3
)
ADSL <- synthetic_cdisc_data("latest")$adsl
app <- init(
data = cdisc_data(
cdisc_dataset("ADSL", ADSL,
code = "ADSL <- synthetic_cdisc_data(\"latest\")$adsl",
metadata = list("Author" = "NEST team", "data_source" = "synthetic data")
),
check = TRUE
),
tm_front_page(
header_text = c(
"Important information" = "It can go here.",
"Other …
```
> allow easy close for front page module

- NEWS.md
- R/tm_variable_browser.R
- man/tm_variable_browser.Rd
Closes [this issue](https://github.com/insightsengineering/teal.modules.general/issues/312).
Added collapsible slider to allow user to manipulate text size in plots.
Patched applying theme to plots.
Added aliases for module documentation.
> [UAT] scale text on the variable browser plot with the plot hieght and width #312

- NEWS.md
- R/tm_g_distribution.R
Add a conditional to hide `Theoretical distibution` panel when `Frequency` is selected as a plot choice.
EDIT: There is also a warning that is rendered on the main branch when tying to plot the theoretical distribution, this has been fixed by passing a `name` and not a `character` function name to the `fun` argument in `stat_function`.
Please test both cases above with the example app.
> hide theoretical distribution

- R/tm_g_bivariate.R
- R/tm_g_response.R
- R/tm_g_scatterplot.R
- R/tm_outliers.R
- turn `categorical_var`  to use generic data-extract-spec instead of handling filter_spec only. Removed custom handling of the NA in the module. Theoretically, this NA problem could exist in every module where user could provide similar settings.
- No validation on the filter - we can't expect specific filter selection in the data_extract_spec - consequently we could do the same in the rest of the modules.
> Fix des outliers@420 shinyvalidate@main

- R/tm_a_pca.R
- R/tm_a_regression.R
- R/tm_g_association.R
- R/tm_g_bivariate.R
- R/tm_g_distribution.R
- R/tm_g_response.R
- R/tm_g_scatterplot.R
- R/tm_missing_data.R
- R/tm_outliers.R
reverted replace of square bracket by `get_var`. Problem with `get_var` is as follows.
- `get_var(object = qenv(), object = "varname")` is dispatched on `object` and there are variants for `qenv` and `qenv.error`. Sometimes `qenv()` can be a shiny-validation-error which causes error message like `no get_var method for object error bla bla`.
- `[[` is generic exported from base and we have extra `[[.qenv` and `[[.qenverror` and this function have also other variants created in base - so that it doesn't fail when calling `<simpleError>[["varname"]]`
It means that to fix problem of plot printed to devide we need to use `teal.code::supress_dev()` in specific cases. We don't need to depend on a `get_var`
> Revert square bracket@main

- NEWS.md
- R/tm_variable_browser.R
- man/render_tab_table.Rd
Fixes #545
Fixes https://github.com/insightsengineering/teal.gallery/issues/19
- Restores the selection based on the selection _(using variable name instead of indexes)_
- Restores the page _(non-trivial as it needs to calculate the index of the first row in the table)_
- uses `displayStart` to set the first row of the page of the selected item
> 545 Keep selected variable in var browser as filters are changed

- R/tm_outliers.R
Fixes #561
Prefer using `other` parameter of the function instead of hardcoded value.
note: The second call of `rule_diff()` is redundant and could be removed, I haven't as it could have been added to prevent some edge case.
> 561 Allow the selection of a categorical variable in `tm_outliers`

- R/tm_g_bivariate.R
- Fixes #559
- Partially implements #560
- The bug that is described there, not the issue itself
* Small change for outliers module to be consistent with others
* Adds `grid::grid.new.page()` call so that reproducible code prints the plot to a new grid instead of an existing one
* Very small change that was included on this PR for practicality
> 559 Change order of `Show R code`/`Show warnings` buttons to be consistent with other modules

- R/tm_a_pca.R
> 570 horizontal lines

- DESCRIPTION
- NEWS.md
Releasing 0.2.16
Linking with:
https://github.com/insightsengineering/nestdevs-tasks/issues/25
> release 0.2.16 [skip vbump] [skip spelling]

- R/tm_variable_browser.R
- inst/css/custom.css
This fixes https://github.com/insightsengineering/teal.modules.general/issues/564
To ensure a neat and compact arrangement of `switchInput `and `slider`, I've employed a line break. instead of adding new classes.
> Unified Visual Consistency for UI Components#564

- R/tm_g_distribution.R
- R/tm_g_scatterplot.R
- R/tm_outliers.R
Fixes #558
Adds tables to `Show R code` shown on screen for different modules
- `tm_g_distribution`: simple "print" of existing table to qenv
- `tm_g_scatterplot.R`: simple "print" of existing table to qenv
- `tm_outliers.R`
- Complex change that adds an extended data frame enriched with additional columns shown in table
- Solution doesn't keep repetitive code
- Keeps previous workflow as much as it can
- Possible alternative solution _(easier)_
- This would just print the ANL_OUTLIERS that only has 6 columns
- Run locally the `exploratory` application of `teal.gallery`
- Open the modules and test the module while observing/running the `Show R code`
- Brush selection to see if previous behaviour is kept
- Filters the table, but not the code
- Adding selected columns in `Outliers` table …
> Add tables to `show-r-code` in distribution, scatterplot and outliers modules

- .pre-commit-config.yaml
Fixes https://github.com/insightsengineering/coredev-tasks/issues/471
- Using GitHub packages for `teal.code`, `teal.logger`, `teal.reporter` _(instead of CRAN)_
- For consistency across pre-commit
- Had to add `ie/teal.data` as it's not on CRAN yet and it's needed by multiple dependencies
> Only retain hard dependencies from pre-commit hooks

- R/tm_variable_browser.R
Part of fix for [#485](https://github.com/insightsengineering/coredev-tasks/issues/458)
> Replace the `qplot` function with `ggplot` equivalent

- NEWS.md
- R/tm_g_response.R
> Apply facet rule only when supplied

- R/tm_g_scatterplotmatrix.R
Example App
```
ADRS <- teal.modules.general::rADRS
})
datanames <- c("ADSL", "ADRS")
data = data,
teal.modules.general::tm_g_scatterplotmatrix(
label = "Scatterplot matrix",
variables = list(
teal.transform::data_extract_spec(
select = select_spec(
label = "Select variables:",
choices = variable_choices(data[["ADSL"]]),
selected = c("AGE", "RACE", "SEX"),
multiple = TRUE,
ordered = TRUE,
fixed = FALSE
)
),
teal.transform::data_extract_spec(
dataname = "ADRS",
filter = teal.transform::filter_spec(
label = "Select endpoints:",
vars = c("PARAMCD", "AVISIT"),
choices = …
```
> `tdata` to `teal_data` - `tm_g_scatterplotmatrix`

- R/tm_a_pca.R
**Example App**
```
})
data = data,
teal.modules.general::tm_a_pca(
"PCA",
dat = teal.transform::data_extract_spec(
choices = teal.transform::variable_choices(
data = data[["ADSL"]], c("BMRKR1", "AGE", "EOSDY")
),
selected = c("BMRKR1", "AGE"),
multiple = TRUE
),
filter = NULL
),
ggplot2_args = teal.widgets::ggplot2_args(
labs = list(subtitle = "Plot generated by PCA Module")
)
)
)
)
shinyApp(app$ui, app$server)
```
> `tdata` to `teal_data` - `tm_a_pca`

- R/tm_a_regression.R
**Example App**
```
})
data = data,
teal.modules.general::tm_a_regression(
label = "Regression",
response = teal.transform::data_extract_spec(
choices = "BMRKR1",
selected = "BMRKR1",
fixed = TRUE
)
),
regressor = teal.transform::data_extract_spec(
label = "Select variables:",
choices = teal.transform::variable_choices(data[["ADSL"]], c("AGE", "SEX", "RACE")),
multiple = …
```
> `tdata` to `teal_data` - `tm_a_regression`

- R/tm_g_response.R
```
})
data = data,
teal.modules.general::tm_g_response(
label = "Response Plots",
response = teal.transform::data_extract_spec(
choices = teal.transform::variable_choices(data[["ADSL"]], c("BMRKR2", "COUNTRY")),
selected = "BMRKR2",
fixed = FALSE
)
),
x = teal.transform::data_extract_spec(
choices = teal.transform::variable_choices(data[["ADSL"]], c("SEX", …
```
> `tdata` to `teal_data` - `tm_g_response`

- R/tm_data_table.R
- R/tm_missing_data.R
- R/tm_variable_browser.R
- man/tm_data_table.Rd
- man/tm_missing_data.Rd
- man/tm_variable_browser.Rd
this fixes https://github.com/insightsengineering/teal.modules.general/issues/619
Here, I am filtering `datanames `to only allow` data.frame` class and skipping other classes. Should we notify the user about datanames which are skipped ?
> 619 update modules to handle default datanames when datanames = "all"

- R/tm_g_bivariate.R
- R/tm_g_distribution.R
- R/tm_g_response.R
- R/tm_g_scatterplot.R
- R/tm_missing_data.R
- R/tm_outliers.R
- R/tm_t_crosstable.R
- R/utils.R
- man/shared_params.Rd
Part of #624
From this https://github.com/insightsengineering/teal.modules.general/issues/624#issuecomment-1957830948
- Adds `@return` tag to `shared_params` to be reused across all documentation
- Corrects linter errors
> Adds common `@return` for modules and corrects linting

- .pre-commit-config.yaml
- DESCRIPTION
Part of #624
Follow-up to:
- #643
- Removes `magrittr` from `Config/Needs/verdepcheck`
- Re-order `verdpecheck` with same order on `Depends`, `Imports`, `Suggests`
- Re-order `pre-commit` config with same order on `Depends`, `Imports`, `Suggests`
- Add remote repo to `htmlwidgets/sparkline` (despite not being updated in years) in `verdepcheck`
> pre-release: Update verdpecheck and pre-commit

- R/tm_a_pca.R
- R/tm_a_regression.R
- R/tm_g_association.R
- R/tm_g_bivariate.R
- R/tm_g_distribution.R
- R/tm_g_scatterplot.R
- R/tm_g_scatterplotmatrix.R
- R/tm_missing_data.R
- R/tm_outliers.R
- R/utils.R
- man-roxygen/ggplot2_args_multi.R
- man/get_scatterplotmatrix_stats.Rd
- man/include_css_files.Rd
- man/shared_params.Rd
- man/tm_a_pca.Rd
- man/tm_a_regression.Rd
- man/tm_data_table.Rd
- man/tm_g_association.Rd
- man/tm_g_bivariate.Rd
- man/tm_g_distribution.Rd
- man/tm_g_response.Rd
- man/tm_g_scatterplot.Rd
- man/tm_g_scatterplotmatrix.Rd
- man/tm_missing_data.Rd
- man/tm_outliers.Rd
- man/tm_t_crosstable.Rd
- man/tm_variable_browser.Rd
fixes https://github.com/insightsengineering/teal.modules.general/issues/674
> standardize the notation for optional parameters

- R/tm_g_scatterplot.R
Fixes the following example app:
```r
devtools::load_all()
library(scda)
library(scda.2022)
ADSL <- synthetic_cdisc_dataset("latest", "adsl")
})
datanames <- "ADSL"
ADSL <- data[["ADSL"]]
adsl_extracted_num <- data_extract_spec(
select = select_spec(
choices = variable_choices(ADSL),
fixed = FALSE
)
)
adsl_extracted_num2 <- data_extract_spec(
select = select_spec(
choices = variable_choices(ADSL),
selected = "BMRKR1",
fixed = FALSE
)
)
fact_vars_adsl <- names(Filter(isTRUE, sapply(ADSL, is.factor)))
adsl_extracted_factors <- data_extract_spec(
select = …
```
> Fix the typo on tags$strong

- .github/workflows/check.yaml
- DESCRIPTION
- tests/testthat/helper-TealAppDriver.R
- tests/testthat/helper-testing-depth.R
Part of #712
- Allow `TealAppDriver` to be used in tests
- R6 class is not yet exported from `{teal}` and needs to be used here
- Adds CDISC simple data helper to use in e2e tests
- Adds `skip_if_too_deep` function
> Adds necessary shinytest2 helpers for automated tests

- tests/testthat/helper-TealAppDriver.R
Part of #712 
- Changes `shinyApp` function used in `TealAppDriver` to trick `shinytest2` into loading the package
- This allows the module server function to call package in `Depends` without prefixing
- Checkout branch
- Save test below in the `tests/testthat` directory
- Restart R session (don't load package afterwards!)
- Run `devtools::test(filter = "test-remove_me.R")` or whatever name you use
- Run test interactively after loading package
```r
testthat::test_that("sample test", {
data <- teal.data::teal_data()
require(nestcolor)
CO2 <- CO2
})
teal.data::datanames(data) <- "CO2"
mod <- teal.modules.general::tm_g_scatterplot(
label = "Scatterplot Choices",
x = teal.transform::data_extract_spec(
dataname = "CO2",
label = …
```
> 712 - `{shinytest2}` Injects `library` of tmg for shiny app

- tests/testthat/test-shinytest2-tm_misssing_data.R
A test in tm_missing_data is failing because a slider's default value gives an error. It passed in PR [727](https://github.com/insightsengineering/teal.modules.general/pull/727) with a value of 2L, but here it was showing 1L. I fixed it in PR [733](https://github.com/insightsengineering/teal.modules.general/pull/733) with app_driver$get_active_module_input("iris-combination_cutoff"), but it's causing an error in another PR again.
To fix I have set.seed in` teal_data()`
> fixing shinytest2 fail for tm_missing_data

- vignettes/using-association-plot.Rmd
- vignettes/using-bivariate-plot.Rmd
- vignettes/using-cross-table.Rmd
- vignettes/using-data-table.Rmd
- vignettes/using-outliers-module.Rmd
- vignettes/using-regression-plots.Rmd
- vignettes/using-response-plot.Rmd
- vignettes/using-scatterplot-matrix.Rmd
- vignettes/using-scatterplot.Rmd
- Fixes #740
- Fixes #729
- add `eval=base::interactive()` to chunk options in vignettes
- Run `rmcdcheck::rmcdcheck()`
- Run `scheduled.yaml` Github action and all strategies complete successfully
- Currently they're taking 6h+ hours and failing
- Badge for this branch: [![Scheduled 🕰️](https://github.com/insightsengineering/teal.modules.general/actions/workflows/scheduled.yaml/badge.svg?branch=740-vignettes-shinyapp%40main)](https://github.com/insightsengineering/teal.modules.general/actions/workflows/scheduled.yaml)
> `shinyApp` chunk in vignettes only runs if is in interactive mode

- NEWS.md
- R/tm_a_pca.R
- R/tm_a_regression.R
- R/tm_g_association.R
- R/tm_g_bivariate.R
- R/tm_g_distribution.R
- R/tm_g_response.R
- R/tm_g_scatterplot.R
- R/tm_g_scatterplotmatrix.R
- R/tm_missing_data.R
- R/tm_outliers.R
- R/tm_t_crosstable.R
Part of https://github.com/insightsengineering/teal/issues/1176
> 1176 remove `Show Warnings` from modules

- DESCRIPTION
- NEWS.md
- R/tm_missing_data.R
- tests/testthat/test-shinytest2-tm_a_regression.R
- tests/testthat/test-shinytest2-tm_data_table.R
- tests/testthat/test-shinytest2-tm_file_viewer.R
- tests/testthat/test-shinytest2-tm_front_page.R
- tests/testthat/test-shinytest2-tm_g_association.R
- tests/testthat/test-shinytest2-tm_g_scatterplotmatrix.R
- tests/testthat/test-shinytest2-tm_misssing_data.R
- tests/testthat/test-shinytest2-tm_outliers.R
- tests/testthat/test-shinytest2-tm_t_crosstable.R
- tests/testthat/test-shinytest2-tm_variable_browser.R
Fixes #772
- Convert `data` -> `data()` 
- Use `datanames()` instead of `names()`
> Fixes data reactivity in `tm_missing_data`

- R/tm_variable_browser.R
Fixes #783 
There were a few missing imports that made the package unusable if we want to load functions with `box`.
> Fixes missing imports

- .github/workflows/scheduled.yaml
- DESCRIPTION
- vignettes/teal-modules-general.Rmd
- vignettes/using-association-plot.Rmd
- vignettes/using-bivariate-plot.Rmd
- vignettes/using-cross-table.Rmd
- vignettes/using-data-table.Rmd
- vignettes/using-outliers-module.Rmd
- vignettes/using-regression-plots.Rmd
- vignettes/using-response-plot.Rmd
- vignettes/using-scatterplot-matrix.Rmd
- vignettes/using-scatterplot.Rmd
Fixes #771 
- revdepcheck 🆗  https://github.com/insightsengineering/teal.modules.general/actions/runs/11162906687
- rhub 🌮 WIP https://github.com/insightsengineering/teal.modules.general/actions/runs/11211837075/job/31161572229
This fixes R-hub and revdepcheck checks
> WIP 771 fix failed pipelines

- .pre-commit-config.yaml
Fixes https://github.com/insightsengineering/nestdevs-tasks/issues/85
- Add dependency to pre-commit configuration
> Adds `roxy.shinylive` to pre-commit configuration

- R/tm_t_crosstable.R
- man/tm_t_crosstable.Rd
Part of https://github.com/insightsengineering/teal/issues/1370
<details><summary> Working Example </summary>
````r
devtools::load_all("../teal")
devtools::load_all(".")
split_by_decorator <- teal_transform_module(
label = "Footnote",
ui = function(id) shiny::textInput(
shiny::NS(id, "text"), "Insert row", "Hello World!" 
),
server = function(id, data) {
moduleServer(id, function(input, output, session) {
logger::log_info("🟢 Text called to action!", namespace = "teal.modules.general")
reactive(
within(
data(),
{
table <- table %>% insert_rrow(rrow(text))
},
text = input$text
)
)
})
}
)
ADSL <- rADSL
})
join_keys(data) <- default_cdisc_join_keys[names(data)]
app <- init(
data = data,
tm_t_crosstable(
label = "Cross Table",
x = …
```
> introduce decorators for `tm_t_crosstable`

- DESCRIPTION
> Teal version bump

- R/tm_a_pca.R
- R/tm_a_regression.R
- R/tm_data_table.R
- R/tm_g_association.R
- R/tm_g_bivariate.R
- R/tm_g_distribution.R
- R/tm_g_response.R
- R/tm_g_scatterplot.R
- R/tm_g_scatterplotmatrix.R
- R/tm_missing_data.R
- R/tm_outliers.R
- R/tm_t_crosstable.R
- man/tm_a_pca.Rd
- man/tm_a_regression.Rd
- man/tm_data_table.Rd
- man/tm_g_association.Rd
- man/tm_g_bivariate.Rd
- man/tm_g_distribution.Rd
- man/tm_g_response.Rd
- man/tm_g_scatterplot.Rd
- man/tm_g_scatterplotmatrix.Rd
- man/tm_missing_data.Rd
- man/tm_outliers.Rd
- man/tm_t_crosstable.Rd
Fixes #813
On #814 we only addressed the missing dependency (the first two code blocks), on this PR the issues with the links (the third code block).
`R CMD check` doesn't complain (with 2024-12-07 r87428 ucrt).
See https://github.com/insightsengineering/teal/issues/1420#issuecomment-2535506586 for a longer explanation on why this fixed the links issue.
> Fix documentation note about links on r-devel

- R/utils.R
The same as in tmc
https://github.com/insightsengineering/teal.modules.clinical/pull/1313/commits/b048f3744c475e3a2e19733d0b34d71061548faf
do not allow decorators with duplicated names
> add a check for non-unique decorator names

- .github/workflows/scheduled.yaml
Companion to that allows to use older MultiAssayExperiment and older SummarizedExperiment 
More explanation in here https://github.com/insightsengineering/teal.slice/pull/637#issuecomment-2607373951
https://github.com/insightsengineering/teal/pull/1460
https://github.com/insightsengineering/teal.slice/pull/637
> simplify builds dependencies of extra-deps

- DESCRIPTION
Since new version of teal.reporter is on CRAN
it's a good moment to update teal, the reverse dependency,
so that we can run tests and see if all is passing for the newly released teal.repoter.
teal will be released anyway soon and dependencies would be bumped to releases versions
https://cran.r-project.org/web/packages/teal.reporter/index.html
> Update teal.reporter version

- DESCRIPTION
- NEWS.md
- R/tm_a_pca.R
- R/tm_a_regression.R
- R/tm_g_association.R
- R/tm_g_bivariate.R
- R/tm_g_distribution.R
- R/tm_g_response.R
- R/tm_g_scatterplot.R
- R/tm_t_crosstable.R
Closes #870 
Here are the steps to be done with this PR:
> [skip vbump] [skip actions] Hot fix - upversion v0.4.1

- R/tm_g_distribution.R
> Don't update distribution params labels when variable is deselected in `tm_g_distribution`

- R/tm_file_viewer.R
Fixes #152 
Just adding `search = TRUE` argument
> Allow search in tm_file_viewer

- R/tm_g_distribution.R
- man/srv_decorate_teal_data.Rd
Fixes #510 
* Improve the logic to define `params_names`
<details>
<summary>Example Code 1</summary>
```r
iris <- iris
})
#'
app <- init(
data = data,
modules = list(
tm_g_distribution(
dist_var = data_extract_spec(
dataname = "iris",
select = select_spec(variable_choices("iris"), "Petal.Length")
)
)
)
)
if (interactive()) {
shinyApp(app$ui, app$server)
}
```
</details>
<details>
<summary>Example Code 2 where nothing is selected</summary>
```r
ADSL <- teal.data::rADSL
})
join_keys(data) <- default_cdisc_join_keys[names(data)]
#'
vars1 <- choices_selected(
variable_choices(data[["ADSL"]], c("ARM", "COUNTRY", "SEX")),
selected = NULL
)
#'
app <- init(
data = data,
tm_g_distribution( …
```
> fix label logic

- DESCRIPTION
- R/tm_a_pca.R
- R/tm_a_regression.R
- R/tm_g_association.R
- R/tm_g_bivariate.R
- R/tm_g_distribution.R
- R/tm_g_response.R
- R/tm_g_scatterplot.R
- R/tm_g_scatterplotmatrix.R
- R/tm_missing_data.R
- R/tm_outliers.R
- R/tm_t_crosstable.R
- R/tm_variable_browser.R
Part of https://github.com/insightsengineering/coredev-tasks/issues/650
> Use the the new add button for adding a card

- DESCRIPTION
- NEWS.md
Fixes #876 
* Update DESCRIPTION and NEWS
* vbump all teal.* dependencies
* Remove `Remotes` entries
> [skip vbump] upversion v0.5.0

- R/tm_a_pca.R
- R/tm_a_regression.R
- R/tm_g_association.R
- R/tm_g_bivariate.R
- R/tm_g_distribution.R
- R/tm_g_response.R
- R/tm_g_scatterplot.R
- R/tm_g_scatterplotmatrix.R
- R/tm_missing_data.R
- R/tm_outliers.R
- R/tm_t_crosstable.R
- Part of https://github.com/insightsengineering/teal/issues/1534
Companion to:
- https://github.com/insightsengineering/teal/pull/1592
- https://github.com/insightsengineering/teal.reporter/pull/401
Other similar PRs in modules:
- https://github.com/insightsengineering/teal.modules.clinical/pull/1425
- https://github.com/insightsengineering/teal.modules.general/pull/917
- https://github.com/insightsengineering/teal.goshawk/pull/366
- https://github.com/insightsengineering/teal.osprey/pull/319
> Remove source code button from modules' encoding panel
