insightsengineering/teal.modules.general

README.md
Related to insightsengineering/coredev-tasks#301
=> docs: replaced github links with pkgdown links

DESCRIPTION
=> update desc file

NEWS.md, R/tm_a_pca.R, inst/css/custom.css
=> FIx tm_a_pca overflow table

.github/workflows/check.yaml, DESCRIPTION, NEWS.md, R/tm_a_pca.R, inst/css/custom.css
=> Merge pre-release to main 

NEWS.md, R/tm_g_scatterplot.R
Closes #437 
FYI @donyunardi
Test with roxygen examples
And reflected in the SRC:
And if you try to do something not very sensible...
Will need to also be merged into the new quosure PRs...
=> add log transformation for scatterplot

R/tm_a_pca.R, R/tm_a_regression.R, R/tm_g_association.R, R/tm_g_bivariate.R, R/tm_g_distribution.R, R/tm_g_response.R, R/tm_g_scatterplot.R, R/tm_g_scatterplotmatrix.R, R/tm_missing_data.R, R/tm_outliers.R, R/tm_t_crosstable.R
part of: insightsengineering/teal.code#67
together with: insightsengineering/teal.code#68
=> @code character to expression

NEWS.md, R/tm_g_association.R, R/tm_g_bivariate.R, tests/testthat/test_bivariate_ggplot_call.R
Closes [this issue](https://github.com/insightsengineering/teal.modules.general/issues/399).
Fixed the way the title of the plot panel is generated.
Improved check box labels in the module UI.
Modified labels for histogram Y axis (_Proportional_ -> _Fraction_).
=> Unhelpful title in tm_g_association

R/tm_variable_browser.R
Patches minor mistake related to [this](https://github.com/insightsengineering/teal.modules.general/issues/312).
=> add missing utils prefix

NEWS.md, R/tm_g_scatterplot.R
Fixes #[376](https://github.com/insightsengineering/teal.modules.general/issues/376)
=> 376 facet error@main

DESCRIPTION, NEWS.md, R/tm_a_pca.R, R/tm_a_regression.R, R/tm_g_association.R, R/tm_g_bivariate.R, R/tm_g_distribution.R, R/tm_g_response.R, R/tm_g_scatterplot.R, R/tm_missing_data.R, R/tm_outliers.R, vignettes/using-scatterplot.Rmd
closes #500 
Also prevents R CMD check from failing on vignette _Using scatterplot_ if package `ggExtra` is not installed.
=> make themes non-optional

R/tm_g_distribution.R
closes #505 
Some methods (two way) require `strata_var` arg which is optional. I've excluded these tests from choices
=> Fix strata_var vs test

NEWS.md, R/tm_g_bivariate.R, R/tm_g_distribution.R, R/tm_variable_browser.R
Removed `..density..` and `..count..` and `..prop..` from tmg - closes #508
=> Remove some deprecated ggplot2 functions

R/tm_g_distribution.R
The only place `extract_input` is used is now in the outliers modules so if it's removed there then the function can be deleted
Note found issue https://github.com/insightsengineering/teal.modules.general/issues/510 - which is on main as well
=> Remove extract input from dist

R/teal.modules.general.R
=> make count as globalVariables

R/tm_a_pca.R, R/tm_a_regression.R, R/tm_g_association.R, R/tm_g_bivariate.R, R/tm_g_distribution.R, R/tm_g_response.R, R/tm_g_scatterplot.R, R/tm_g_scatterplotmatrix.R, R/tm_missing_data.R, R/tm_outliers.R, R/tm_t_crosstable.R, R/tm_variable_browser.R, man/tm_a_pca.Rd, man/tm_a_regression.Rd, man/tm_data_table.Rd, man/tm_file_viewer.Rd, man/tm_front_page.Rd, man/tm_g_association.Rd, man/tm_g_bivariate.Rd, man/tm_g_distribution.Rd, man/tm_g_response.Rd, man/tm_g_scatterplot.Rd, man/tm_g_scatterplotmatrix.Rd, man/tm_missing_data.Rd, man/tm_outliers.Rd, man/tm_t_crosstable.Rd, man/tm_variable_browser.Rd
Closes https://github.com/insightsengineering/teal/issues/864
=> Move TealReportCard to teal

R/tm_a_pca.R, R/tm_a_regression.R, R/tm_data_table.R, R/tm_file_viewer.R, R/tm_front_page.R, R/tm_g_association.R, R/tm_g_bivariate.R, R/tm_g_distribution.R, R/tm_g_response.R, R/tm_g_scatterplot.R, R/tm_g_scatterplotmatrix.R, R/tm_missing_data.R, R/tm_outliers.R, R/tm_t_crosstable.R, R/tm_variable_browser.R
Part of [this](https://github.com/insightsengineering/teal/issues/769)
=> propagate argument name change in teal::module

R/tm_a_regression.R, R/tm_g_scatterplot.R
this PR fixes https://github.com/insightsengineering/teal.modules.general/issues/554
=> [Bug]: plots from tm_g_scatterplot and tm_a_regression modules print on IDE 554

R/tm_missing_data.R, R/tm_t_crosstable.R
this fixes https://github.com/insightsengineering/teal.modules.general/issues/568
=> Fixing inconsistent Styling and Layout for 'Show Warning' and 'Show R Code' Buttons

R/tm_data_table.R, R/tm_g_distribution.R
this fixes https://github.com/insightsengineering/teal.modules.general/issues/566
=> 566 Consistent white background for modules 

R/tm_variable_browser.R, man/plot_var_summary.Rd
this fixes https://github.com/insightsengineering/teal.modules.general/issues/556
=> 556 Longer labels for x axis in the `tm_variable_browser()` are not fully displayed

NEWS.md, R/tm_g_scatterplotmatrix.R, R/tm_outliers.R
=> Make sure to pass a `data.frame` into `teal::validate_has_data`

R/tm_g_distribution.R
```
iris <- iris
})
datanames(data) <- c("iris")
data = data,
modules = list(
teal.modules.general::tm_g_distribution(
dist_var = teal.transform::data_extract_spec(
dataname = "iris",
select = teal.transform::select_spec(variable_choices("iris"), "Petal.Length")
),
ggplot2_args = teal.widgets::ggplot2_args(
labs = list(subtitle = "Plot generated by Distribution Module")
)
)
)
)
if (interactive()) {
shinyApp(app$ui, app$server)
}
})
vars1 <- choices_selected(
variable_choices(data[["ADSL"]], c("ARM", "COUNTRY", "SEX")),
selected = NULL
)
app <- …
```
=> `tdata` to `teal_data` - `tm_g_distribution`

R/tm_g_bivariate.R
```
})
data = data,
teal.modules.general::tm_g_bivariate(
x = teal.transform::data_extract_spec(
choices = teal.transform::variable_choices(data[["ADSL"]]),
fixed = FALSE
)
),
y = teal.transform::data_extract_spec(
choices = teal.transform::variable_choices(data[["ADSL"]]),
selected = "SEX",
fixed = FALSE
)
),
row_facet = …
```
=> `tdata` to `teal_data` - `tm_g_bivariate`

R/tm_outliers.R
Example App
```
})
fact_vars_adsl <- names(Filter(isTRUE, sapply(data[["ADSL"]], is.factor)))
vars <- choices_selected(variable_choices(data[["ADSL"]], fact_vars_adsl))
data = data,
teal.modules.general::tm_outliers(
outlier_var = list(
teal.transform::data_extract_spec(
select = select_spec(
choices = variable_choices(data[["ADSL"]], c("AGE", "BMRKR1")),
fixed = FALSE
)
)
),
categorical_var = list(
teal.transform::data_extract_spec(
filter = …
```
=> `tdata` to `teal_data` - `tm_outliers`

R/tm_g_scatterplot.R
Example App
```
})
data = data,
teal.modules.general::tm_g_scatterplot(
label = "Scatterplot Choices",
x = teal.transform::data_extract_spec(
choices = teal.transform::variable_choices(
data[["ADSL"]],
c("AGE", "BMRKR1", "BMRKR2")
),
fixed = FALSE
)
),
y = teal.transform::data_extract_spec(
choices = teal.transform::variable_choices( …
```
=> `tdata` to `teal_data` - `tm_g_scatterplot`

R/tm_a_pca.R, R/tm_a_regression.R, R/tm_g_association.R, R/tm_g_bivariate.R, R/tm_g_distribution.R, R/tm_g_response.R, R/tm_g_scatterplot.R, R/tm_g_scatterplotmatrix.R, R/tm_missing_data.R, R/tm_outliers.R, R/tm_t_crosstable.R
part of https://github.com/insightsengineering/teal.code/pull/176
=> `get_code` to return concatenated code string

DESCRIPTION, NEWS.md, R/tm_variable_browser.R
companion to https://github.com/insightsengineering/teal.slice/pull/508
=> 507 reevaluate `variable_types`

DESCRIPTION, inst/WORDLIST, man/teal.modules.general.Rd, man/tm_a_pca.Rd, man/tm_a_regression.Rd, man/tm_data_table.Rd, man/tm_file_viewer.Rd, man/tm_front_page.Rd, man/tm_g_association.Rd, man/tm_g_bivariate.Rd, man/tm_g_distribution.Rd, man/tm_g_response.Rd, man/tm_g_scatterplot.Rd, man/tm_g_scatterplotmatrix.Rd, man/tm_missing_data.Rd, man/tm_outliers.Rd, man/tm_t_crosstable.Rd, man/tm_variable_browser.Rd
Part of https://github.com/insightsengineering/coredev-tasks/issues/506
=> Fix pkgdown redirect

R/utils.R, man/shared_params.Rd
Part of #624
Sorry, I missed a full stop on #670
=> pre-release: Typo with missing a full stop

vignettes/teal-modules-general.Rmd, vignettes/using-association-plot.Rmd, vignettes/using-bivariate-plot.Rmd, vignettes/using-cross-table.Rmd, vignettes/using-data-table.Rmd, vignettes/using-outliers-module.Rmd, vignettes/using-regression-plots.Rmd, vignettes/using-response-plot.Rmd, vignettes/using-scatterplot-matrix.Rmd, vignettes/using-scatterplot.Rmd
=> docs: update the vignette author to "NEST CoreDev"

R/tm_a_pca.R
=> Fix the silent error in `tm_a_pca`

R/tm_variable_browser.R
=> Store the user selections so our default selection logic can be applied

R/tm_g_bivariate.R
fixes https://github.com/insightsengineering/teal.modules.general/issues/701
=> 701 fixing the validation issue for x/y variable selection in `tm_g_bivariate`.

R/tm_a_pca.R, R/tm_a_regression.R, R/tm_data_table.R, R/tm_file_viewer.R, R/tm_g_association.R, R/tm_g_bivariate.R, R/tm_g_distribution.R, R/tm_g_response.R, R/tm_g_scatterplot.R, R/tm_g_scatterplotmatrix.R, R/tm_missing_data.R, R/tm_outliers.R, R/tm_t_crosstable.R, R/tm_variable_browser.R, R/utils.R, man/tm_g_distribution.Rd
part of https://github.com/insightsengineering/teal.slice/issues/445
for teal.modules.general package
=> 445 unify html tags

R/tm_g_distribution.R
Adds bookmark exclusion in tm_g_distribution.
=> fix after adding bookmarks

DESCRIPTION
Companion to 
https://github.com/insightsengineering/teal/pull/1464
=> Update `teal.code` version

.github/workflows/check.yaml, .github/workflows/docs.yaml, .github/workflows/release.yaml, .github/workflows/scheduled.yaml, DESCRIPTION
vbump teal.data to released version
=> vbump teal.data

R/tm_data_table.R, R/tm_front_page.R, R/tm_variable_browser.R, man/tm_data_table.Rd, man/tm_front_page.Rd, man/tm_g_distribution.Rd, man/tm_variable_browser.Rd
`transformators` arg is addressed in `teal`. Every module which has `data` in the server needs a `transformators` argument
=> Add missing transformators arg

R/tm_a_pca.R, R/tm_g_bivariate.R, R/tm_g_distribution.R, R/tm_variable_browser.R
=> add ggplot2 prefix

R/tm_a_pca.R, R/tm_file_viewer.R, R/tm_outliers.R, inst/css/custom.css
Part of https://github.com/insightsengineering/teal/issues/1505
=> Final UI and bslib changes

R/tm_g_scatterplot.R
Fixes #19 
The plot is now generated as long as the dataset has at least one row.
<details>
<summary>Example code</summary>
```r
require(nestcolor)
CO2 <- CO2
})
#'
app <- init(
data = data,
tm_g_scatterplot(
label = "Scatterplot Choices",
x = data_extract_spec(
dataname = "CO2",
select = select_spec(
choices = variable_choices(data[["CO2"]], c("conc", "uptake")),
selected = "conc",
fixed = FALSE
)
),
y = data_extract_spec(
dataname = "CO2",
select = select_spec(
choices = variable_choices(data[["CO2"]], c("conc", "uptake")),
selected = "uptake",
fixed = FALSE
)
),
color_by = data_extract_spec(
dataname = "CO2",
select = select_spec( …
```
=> update nrows validation in scatterplot

R/utils.R, man/srv_decorate_teal_data.Rd
- Changes from `teal_reportable` branch at `{ŧeal.report}`
- Remove old logic that was defusing the argument
=> feat: support argument rename and clean function body

NEWS.md, R/tm_g_association.R
=> Fixes deprecation warning in `tm_g_association`

R/utils.R
Related to https://github.com/insightsengineering/teal.osprey/pull/308/files/88116b9e9c4886713a95640b4b88d21e3d138eea..97c0d2b36c460e04249a3ba53e2f5ab20d948a6e#r2343928335
=> Refactor conditional statement for inner_classes check

NEWS.md, R/tm_g_distribution.R
- Fixes #920
- Fixes problem in code
- Adds missing section in `NEWS.md` with reporter refactor.
- Test this module beyond the original issue scope
- Both plots and more combinations of enconding
=> Fixes `tm_g_distribtution` from not properly creating report
